# Generated by Django 5.0 on 2024-01-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='image/default.jpeg', null=True, upload_to='image'),
        ),
    ]
